pipeline {
  agent any
  tools {
    nodejs 'node-11.0.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        bat('cd jenkins-tests && npm install')
      }
    }
    
    stage('Run tests') {
      steps {
        bat('cd jenkins-tests && npm test')
      }
    }
    
    stage('Run remote'){
        steps {
            build wait: false, job: 'parameterized', parameters: [string(name: 'ROOT_ID', value: '$BUILD_ID')]
        }
    }
    
  }
}
